# your necessary environment based variable needs to be here.
# please make sure left side of the equal sign is upper case and right side as you want it to be
# there could be a lot of time your environment is not reaching out your desired one from below references,
# in those cases please make sure your configuration.properties file under the desired environment like
# dev/test/prod/uat/stage

ENVIRONMENT=prod
API=true
API.REPORT.PRINT=true
Request.Print=true
RESPONSE.PRINT=true
API.SAVE.REQUEST.AND.RESPONSE=true

App.NAME=FAMILY
DESIGN=
SERVICE.NAME=FAMILY
USE=EXCEL

DATABASE.DRIVER=org.postgresql.Driver
DATABASE.URL=prod-mir.amazonaws.com
DATABASE.USERNAME=prod-mir-database
DATABASE.PASSWORD=

MIR.SERVICE.UI.URL=https://playwright.dev
FILE.SERVICE.API.URL=https://url/
MIR.SERVICE.API.URL=https://url2/
ADMINISTRATION.SERVICE.API.URL=https://url3/
SUBMISSION.SUPPORT.SERVICE.API.URL=https://url4/
PROFILE.SERVICE.API.URL=https://url4/
MIR.2.KIDS.SERVICE.API.URL=https://url5/
WIFE.SERVICE.API.URL=https://url6/